### ISSUE TITLE
Admin / Granted and pending requests - Bug when user account has been deleted

### ISSUE THREAD

**Issue by ahukkanen** [mainio/decidim-module-access_requests#5]
The admin panel listing for granted and pending access requests breaks in case the account to be listed does not have a nickname, i.e. is removed.

This breaks because Decidim cannot figure out a proper URL for a user account without a nickname.

Related to the following lines in the code:
https://github.com/mainio/decidim-module-access_requests/blob/ebd5e33e286843aace313d67a15735c6fd9ed93a/app/views/decidim/access_requests/verification/admin/granted_authorizations/index.html.erb#L29
https://github.com/mainio/decidim-module-access_requests/blob/ebd5e33e286843aace313d67a15735c6fd9ed93a/app/views/decidim/access_requests/verification/admin/pending_authorizations/index.html.erb#L28

## Stacktrace

```
, [2020-02-19T11:57:28.346942 #16071] FATAL -- : []   
F, [2020-02-19T11:57:28.347054 #16071] FATAL -- : [] ActionView::Template::Error (No route matches {:action=>"show", :controller=>"decidim/profiles", :nickname=>""}, possible unmatched constraints: [:nickname]):
F, [2020-02-19T11:57:28.347164 #16071] FATAL -- : []     26:             </td>
[]     27:             <td class="table-list__actions">
[]     28:               <%= icon_link_to "person",
[]     29:                                decidim.profile_path(authorization.user.nickname),
[]     30:                                t("layouts.decidim.user_profile.account"),
[]     31:                                class:"action-icon--show",
[]     32:                                target: "_blank" %>
F, [2020-02-19T11:57:28.347205 #16071] FATAL -- : []   
F, [2020-02-19T11:57:28.347269 #16071] FATAL -- : [] actionpack (5.2.4.1) lib/action_dispatch/journey/formatter.rb:57:in `generate'
[] actionpack (5.2.4.1) lib/action_dispatch/routing/route_set.rb:744:in `generate'
[] actionpack (5.2.4.1) lib/action_dispatch/routing/route_set.rb:775:in `generate'
[] actionpack (5.2.4.1) lib/action_dispatch/routing/route_set.rb:822:in `url_for'
[] actionpack (5.2.4.1) lib/action_dispatch/routing/route_set.rb:273:in `call'
[] actionpack (5.2.4.1) lib/action_dispatch/routing/route_set.rb:331:in `block (2 levels) in define_url_helper'
[] actionpack (5.2.4.1) lib/action_dispatch/routing/routes_proxy.rb:45:in `profile_path'
[] decidim-access_requests (0.19.0) app/views/decidim/access_requests/verification/admin/granted_authorizations/index.html.erb:29:in `block in __home_hkidecidimprod_production_shared_bundle_ruby_______gems_decidim_access_requests________app_views_decidim_access_requests_verification_admin_granted_authorizations_index_html_erb___3583623898633805996_47018062004240'
```

**Comment by ahukkanen** [comment]
Fixed by:
https://github.com/mainio/decidim-module-access_requests/commit/851c31eb56ad34cd370201fb350d63e9c9a601ea
